name: NoSubVod
options:
  bundleIdPrefix: com.theorhd
  deploymentTarget:
    iOS: 17.0

packages:
  TSPlayerKit:
    url: https://github.com/Theorhd/TSPlayerKit
    branch: main

targets:
  NoSubVod:
    type: application
    platform: iOS
    sources: Sources
    dependencies:
      - package: TSPlayerKit
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UIBackgroundModes:
          - audio
          - fetch
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
