name: NoSubVod
options:
  bundleIdPrefix: com.theorhd
  deploymentTarget:
    iOS: 17.0

packages:
  TSPlayerKit:
    url: https://github.com/Theorhd/TSPlayerKit
    from: 1.0.1

targets:
  NoSubVod:
    type: application
    platform: iOS
    sources: Sources
    dependencies:
      - package: TSPlayerKit
    info:
      path: Info.plist
      properties:
        CFBundleShortVersionString: "1.1"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UIBackgroundModes:
          - audio
          - fetch
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true

  NoSubVodTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/NoSubVodTests
      - path: Tests/Fixtures
        type: folder
    dependencies:
      - target: NoSubVod
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.theorhd.NoSubVodTests
      INFOPLIST_FILE: Tests/NoSubVodTests/Info.plist
